### ISSUE TITLE
Understanding Flakes

### ISSUE THREAD

**Issue by suhr** [nrdxp/nixflk#19] opened 2020-08-05 16:51 UTC
I'm trying to migrate to the new Flake world. The problem is, this template is so complicated it's almost impossible understand how it actually works.

So I started to build my configuration from scratch: https://gist.github.com/suhr/4bb1f8434d0622588b23f9fe13e79973

But there's no documentation for the new stuff. So here I will ask questions about how to do things using Flakes.

**Comment by suhr** [comment] 2020-08-05 16:55
Is there a way to get the home-manager command back?

I tried to do the following:

```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs-channels/nixos-unstable";
    nixpkgs-stable = {
      url = "github:NixOS/nixpkgs/nixos-20.03";
      flake = false;
    };
    home.url = github:rycee/home-manager/bqv-flakes;
    nur.url = github:nix-community/NUR;
  };

  outputs = { nixpkgs, nix, self, ... }@inputs: {
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        (import ./configuration.nix)
        inputs.home.nixosModules.home-manager
      ];
      specialArgs = { inherit inputs; };
    };
    legacyPackages.x86_64-linux = self.nixosConfigurations.nixos.pkgs;
  };
}
```

Then I added `home-manager.users.suhr.programs.home-manager.enable = true;` to the system configuration.

`nixos-rebuild switch` ran without problems. But there's no `home-manager` at the user side.

**Comment by cruizh** [comment] 2020-08-13 21:55
> `nixos-rebuild switch` ran without problems. But there's no `home-manager` at the user side.

It seems that this is intended behaviour from `home-manager`. See the setting for `home-manager.users.<name?>.programs.home-manager` at [<home-manager/modules/programs/home-manager.nix>](https://github.com/rycee/home-manager/blob/master/modules/programs/home-manager.nix#L33). This checks not only that `home-manager` is enabled but also that [`submoduleSupport`](https://github.com/rycee/home-manager/blob/a144c723a11cafbb01f01b5d581be453d2947aa8/modules/misc/submodule-support.nix#L8-L17) is disabled (and in this case it's not). This seems to come from the first ever commit with module support (rycee/home-manager@1bc59f729047886b845ffd9162d40593fad5c7f0).

As far as I understand (and take this with a grain of salt), you should probably just manage the `home-manager` generations as part of the whole system generations, and therefore there should be no need to use the `home-manager` CLI tool.

**Comment by suhr** [comment] 2020-08-14 06:55
Yeah, I figured out that home-manager does not support cli with flakes. I use a flake to manage user packages now. It would be nice to have something to manage some configuration as well though.

**Comment by nrdxp** [comment] 2020-09-26 23:55
I'm going to close this as it really isn't related to the project. However, I am hoping to update the documentation to be a bit more thorough in the near future.

**Closed by nrdxp** 2020-09-26 23:55 UTC
