### ISSUE TITLE
home-manager activate segmentation fault following readme.md upon rebuild NixOS test

### ISSUE THREAD

**Issue by codygman** [nrdxp/nixflk#22] opened 2020-10-17 17:31 UTC
**Describe the bug**
While following the readme at d897b364c6c55e7ccedb6f0b7f7420684b745c8a and making no changes running `rebuild NixOS test` resulted in a segmentation fault:

**To Reproduce**
```
$ nix flake new -t "github:nrdxp/nixflk" flk
$ cd flk 
$ nix-shell

... snip ...

building '/nix/store/xhqx56n4flybrk9z3bzv58hgp92rc4xi-home-manager-path.drv'...
building '/nix/store/m37r9kcx2x11h4ycczvmgz0wg5a7rx3f-activation-script.drv'...
building '/nix/store/y5xrjk2ysyf1y2nv6b828g48k2yrcnps-home-manager-generation.drv'...
building '/nix/store/xaq18p9syfqkj2zfgspm6pyc2wl2p9pi-activate-nixos.drv'...
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
builder for '/nix/store/92pvh7yjcycnzhj3v5g28y4n2s6rvz3f-extra-utils.drv' failed with exit code 139; last 10 log lines:
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in \u2018/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/ata_id\u2019
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/busybox...
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/fido_id...
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in \u2018/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/fido_id\u2019
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/cdrom_id...
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in \u2018/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/cdrom_id\u2019
  testing patched programs...
  hello world
  /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 101:  6309 Done                    $out/bin/mount --help 2>&1
        6310 Segmentation fault      (core dumped) | grep -q "BusyBox"
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/xin3hp61li5y1xmgij155h5md98qa7kz-stage-1-init.sh.drv' failed to build
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/dhhcji9jshnsmlbhwp64qlsifhiqclcz-initrd-linux-5.4.54.drv' failed to build
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/qh6nk4abfpn0h1jy7v6flggd1swnq8ws-nixos-system-NixOS-20.03.20200802.7dc4385.drv' failed to build
```

**Expected behavior**
My configuration is switched to the flake based one until reboot.

**Additional context**
N/A

**Comment by codygman** [comment] 2020-10-29 13:13
I also tested with flk-bare:

```
[cody@nixos:~]$ nix flake new -t "github:nrdxp/nixflk/bare" flk-bare

[cody@nixos:~]$ cd flk-bare/

[cody@nixos:~/flk-bare]$ rebuild NixOS test
evaluating file '/nix/store/2qc98g8pw1yv3kvh1yczwdjazgj14rw4-nix-2.4pre20200721_ff314f1/share/nix/corepkgs/derivation.nix'
evaluating file '/nix/store/iwn67px8m720v5rl3axj52qcab60p3ng-source/flake.nix'
building '/nix/store/92pvh7yjcycnzhj3v5g28y4n2s6rvz3f-extra-utils.drv'...
error: --- Error --------------------------------------------------- nix
builder for '/nix/store/92pvh7yjcycnzhj3v5g28y4n2s6rvz3f-extra-utils.drv' failed with exit code 139; last 10 log lines:
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in ‘/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/ata_id’
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/busybox...
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/fido_id...
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in ‘/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/fido_id’
  patching /nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/cdrom_id...
  warning: working around a Linux kernel bug by creating a hole of 4096 bytes in ‘/nix/store/q9jwr9p86gzrbyb8h5zvl8rg60hm513r-extra-utils/bin/cdrom_id’
  testing patched programs...
  hello world
  /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 101:  6309 Done                    $out/bin/mount --help 2>&1
        6310 Segmentation fault      (core dumped) | grep -q "BusyBox"
error: --- Error --------------------------------------------------- nix
1 dependencies of derivation '/nix/store/xin3hp61li5y1xmgij155h5md98qa7kz-stage-1-init.sh.drv' failed to build
error: --- Error --------------------------------------------------- nix
1 dependencies of derivation '/nix/store/dhhcji9jshnsmlbhwp64qlsifhiqclcz-initrd-linux-5.4.54.drv' failed to build
error: --- Error --------------------------------------------------- nix
1 dependencies of derivation '/nix/store/wl9n175ss57zw8wwr6r1n6vxbsxl17qb-nixos-system-NixOS-20.03.20200802.7dc4385.drv' failed to build
```

**Comment by adamscott** [comment] 2020-11-03 18:39
@codygman I found a way past a similar error (mine was silent) when building the extra-utils derivation. It seems that's an error that was fixed and merged in a later release of NixOS. (https://github.com/NixOS/nixpkgs/issues/96197)

So, I made this work by updating NixOS to 20.09 by editing some lines of `flake.nix` but I think it causes some problems down the line. But I think this works, give me some feedback.

(I updated the repo name too, just because it changed)

 ```nix
{
  # Updated part
  inputs =
    {
      master.url = "nixpkgs/master";
      nixos.url = "nixpkgs/release-20.09";
      home.url = "github:nix-community/home-manager/bqv-flakes";
    };
}
```

**Comment by codygman** [comment] 2020-11-10 02:06
Thanks @adamscott, I tried it but this happened:

```
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------- nix
builder for '/nix/store/mkc1av0vvh8b49xz58cswvmvalg7fmrc-manual-combined.drv' failed with exit code 3; last 10 log lines:
  /nix/store/6z1wciw37k2a7d5r741229pr2qx3hcbg-manual-combined/manual-combined.xml:12545: element xref: validity error : IDREF attribute linkend references an unknown ID "opt-home.file._name__.source"
   12541   <simpara>This release has the following notable changes:</simpara>
   12542     <itemizedlist>
   12543 <listitem>
   12544     <simpara>
   12545      The <xref linkend="opt-home.file._name__.source"/> option now allows source files to be
   12546        hidden, that is, having a name starting with the <literal>.</literal> character. It
   12547    also allows the source file name to contain characters not typically
  
  /nix/store/6z1wciw37k2a7d5r741229pr2qx3hcbg-manual-combined/manual-combined.xml fails to validate
building '/nix/store/p4476hxfn2n8ijpxca8vrj9bwcmbcd1j-groupdel.pam.drv'...
building '/nix/store/wm4a4035nnk8p7q10xa82czvfjag7vhq-groupmems.pam.drv'...
building '/nix/store/kx44mxq71v5k4alfdsvyg690pjpppny5-groupmod.pam.drv'...
building '/nix/store/dgdl4z7ydm8jb968nlwkd0yycnh0mla3-i3lock-color.pam.drv'...
```

With this diff:

```diff
diff --git a/flake.lock b/flake.lock
index 45b4342..26f862f 100644
--- a/flake.lock
+++ b/flake.lock
@@ -5,11 +5,11 @@
         "nixpkgs": "nixpkgs"
       },
       "locked": {
-        "lastModified": 1591751635,
-        "narHash": "sha256-KgGtyFlkI/fsp+j8VEgJ/ynY9B91aX35Xp04HlDLRTo=",
+        "lastModified": 1600463964,
+        "narHash": "sha256-sMOleAVVaEzD2oc0TNnODFTv8rCKau7c1N1jWRGiLio=",
         "owner": "rycee",
         "repo": "home-manager",
-        "rev": "b3fee796fcd5531693d9b84ece76ad6836bb1cfa",
+        "rev": "c5fbe2c4c2369c7fa565e806556444c1346eb015",
         "type": "github"
       },
       "original": {
@@ -21,11 +21,11 @@
     },
     "master": {
       "locked": {
-        "lastModified": 1596337980,
-        "narHash": "sha256-LyE4haB7x2SBb1AyFJwqtGQitdaBFyK2ov4eH9Agono=",
+        "lastModified": 1604970315,
+        "narHash": "sha256-czk4DAvEd75jmh+PYlIpCoKhhfvhLgSYLNFSfTuPbV0=",
         "owner": "NixOS",
         "repo": "nixpkgs",
-        "rev": "111221b93ad46bb7119686f0a89a7bf1d3ad5bd7",
+        "rev": "3aca0e1e6c2d473525efc2fe083cffe47f44d46f",
         "type": "github"
       },
       "original": {
@@ -36,16 +36,16 @@
     },
     "nixos": {
       "locked": {
-        "lastModified": 1596329181,
-        "narHash": "sha256-q6NSFQnFbpey/RP2LFfYW9Vcpt6CYKO8Q//6TuNBuYM=",
+        "lastModified": 1604949503,
+        "narHash": "sha256-qYVhmVay1HF4WoO3TTTo9CC2j8kNYxo1QehnNuz8d2Y=",
         "owner": "NixOS",
         "repo": "nixpkgs",
-        "rev": "7dc4385dc7b5b2c0dbfecd774cebbc87ac05c061",
+        "rev": "96052f35023070072cd5ac0f17a97a2a2269d5b9",
```

**Comment by codygman** [comment] 2020-11-18 19:03
I can confirm updating inputs to `-20.09` in flake.nix fixes the segmentation fault!

**Comment by diogox** [comment] 2020-12-03 22:18
I'm having the same problem. Did you manage to fix this @codygman? The suggested fix gives me the same output you mentioned.

**Comment by codygman** [comment] 2020-12-04 07:26
> I'm having the same problem. Did you manage to fix this @codygman? The suggested fix gives me the same output you mentioned.

This gets a little farther 

https://github.com/nrdxp/nixflk/pull/25

**Comment by nrdxp** [comment] 2020-12-06 01:20
I just merged some of the open PRs. After doing so, I am unable to reproduce this. Is this still an issue or can I close it out?

**Closed** 2020-12-10 22:18 UTC
