### ISSUE TITLE
host for aarch64 system

### ISSUE THREAD

**Issue by liaowang11** [nrdxp/nixflk#125] opened 2021-02-17 17:57 UTC
**Describe the bug**
Adding an aarch64 system with aarch64 specific packages (like libraspberrypi) gives error:
```
Package ‘libraspberrypi’ in /nix/store/widqcq445r5r4ivh7sdfibhjrpq69jgl-source/pkgs/development/libraries/libraspberrypi/default.nix
:19 is not supported on ‘x86_64-linux’, refusing to evaluate.
```
**To Reproduce**
1. Add `raspi4.nix` to `/hosts`
2. run `flk raspi4 dry-run`
3. errors with content like above

```nix
#raspi4.nix
#…
  environment.systemPackages = with pkgs; [                                     
      libraspberrypi                                                              
   ]; 
#…
```
**Expected behavior**
Dry run should succeed

**Additional context**
I’m trying to use flake to config all my machines. This template is the best I can find, but still does not fully support multi-arch. Have tried hlissner’s dotfiles, also not working.
The dotfiles from [Dunklecat](https://git.sr.ht/~dunklecat/nixos-config/tree/master/item/flake.nix) is the only one I ‘ve found support both aarch64 and x86_64. Hope `flk` can support it.

**Comment by nrdxp** [comment] 2021-02-17 18:24
The only reason I haven't wired up multiarch for configs is because the flake spec doesn't expect system attributes under `nixosConfigurations`, and adding them screws up nixos rebuild and friends. 

I have been thinking about the best way to resolve this, and perhaps a non standard output is the best way for now. You can of course, change the system:
https://github.com/nrdxp/nixflk/blob/77296ff433c0dc6e9b5cad522b6a46dafaa204ba/flake.nix#L53

And it should work, but this will change the system for all your hosts. I think I'll just add a `nixos` output with aarch and i686 configs later today.

**Comment by Pacman99** [comment] 2021-02-17 19:38
AIUI the reason theres no multi-arch nixosConfigurations output like the packages output works, is that it doesn't make sense for the same nixosConfiguration to be used under multiple archs. If you want a aarch64 nixosConfiguration output, your supposed make the nixosSystem specifically for that aarch64 system. And that makes sense with nixflk's structure since each host is meant for one system, so you just make a new host file for your aarch64 system.

I think the main issue is that nixflk doesn't allow changing the system that gets passed to the nixosSystem function since its always "x86_64-linux". As a workaround I think you can override nixpkgs.localSystem to aarch64. From what I saw in nixpkgs, thats where the system input to nixosSystem function gets used. But its set as a default, so you could just do:
`nixpkgs.localSystem = { config = "aarch64-unknown-linux-gnu"; system = "aarch64-linux"; }`
or you could just set crossSystem, if you are building the aarch64 config on an x86_64 system.

I think a better solution would be to allow changing the system, possibly by making a new option for it and passing it to nixosSystem.

**Comment by nrdxp** [comment] 2021-02-17 20:46
The problem is that `nixpkgs.localSystem` is ignored when `nixpkgs.pkgs` is set.

**Comment by nrdxp** [comment] 2021-02-17 23:41
duplicate of #72

**Closed by nrdxp** 2021-02-17 23:41 UTC
Labels: enhancement
